---
abstract: "easier loading of a project's local libs"
author:
  - 'Thomas Klausner <domm@cpan.org>'
build_requires:
  Exporter: '0'
  Module::Build: '0.28'
  Test::More: '0'
  Test::Output: '0'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: lib-projectroot
requires:
  Carp: '0'
  File::Spec::Functions: '0'
  FindBin: '0'
  lib: '0'
  local::lib: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  repository: git://github.com/domm/lib-projectroot.git
version: '1.000'
